<?xml version="1.0" encoding="utf-8"?>
<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
	<ItemGroup>
		<Reference Include="System.IdentityModel.Services" />
		<Reference Include="System.Net.Http" />
		<Reference Include="Adxstudio.Xrm">
			<SpecificVersion>False</SpecificVersion>
			<HintPath>$(AdxstudioFrameworkPath)\Adxstudio.Xrm.dll</HintPath>
			<Private>True</Private>
		</Reference>
		<Reference Include="Adxstudio.Xrm.Files">
			<SpecificVersion>False</SpecificVersion>
			<HintPath>$(AdxstudioFrameworkPath)\Adxstudio.Xrm.Files.dll</HintPath>
			<Private>True</Private>
		</Reference>
		<Reference Include="Adxstudio.Xrm.GlobalSearch">
			<SpecificVersion>False</SpecificVersion>
			<HintPath>$(AdxstudioFrameworkPath)\Adxstudio.Xrm.GlobalSearch.dll</HintPath>
			<Private>True</Private>
		</Reference>
		<Reference Include="Adxstudio.Xrm.GlobalSearch.Services">
			<SpecificVersion>False</SpecificVersion>
			<HintPath>$(AdxstudioFrameworkPath)\Adxstudio.Xrm.GlobalSearch.Services.dll</HintPath>
			<Private>True</Private>
		</Reference>
		<Reference Include="AjaxControlToolkit">
			<SpecificVersion>False</SpecificVersion>
			<HintPath>$(AdxstudioFrameworkPath)\AjaxControlToolkit.dll</HintPath>
			<Private>True</Private>
		</Reference>
		<Reference Include="Antlr3.Runtime">
			<SpecificVersion>False</SpecificVersion>
			<HintPath>$(AdxstudioFrameworkPath)\Antlr3.Runtime.dll</HintPath>
			<Private>True</Private>
		</Reference>
		<Reference Include="AuthorizeNet">
			<SpecificVersion>False</SpecificVersion>
			<HintPath>$(AdxstudioFrameworkPath)\AuthorizeNet.dll</HintPath>
			<Private>True</Private>
		</Reference>
		<Reference Include="AuthorizeNet.Helpers">
			<SpecificVersion>False</SpecificVersion>
			<HintPath>$(AdxstudioFrameworkPath)\AuthorizeNet.Helpers.dll</HintPath>
			<Private>True</Private>
		</Reference>
		<Reference Include="DevTrends.MvcDonutCaching">
			<SpecificVersion>False</SpecificVersion>
			<HintPath>$(AdxstudioFrameworkPath)\DevTrends.MvcDonutCaching.dll</HintPath>
			<Private>True</Private>
		</Reference>
		<Reference Include="DocumentFormat.OpenXml">
			<SpecificVersion>False</SpecificVersion>
			<HintPath>$(AdxstudioFrameworkPath)\DocumentFormat.OpenXml.dll</HintPath>
			<Private>True</Private>
		</Reference>
		<Reference Include="DotLiquid">
			<SpecificVersion>False</SpecificVersion>
			<HintPath>$(AdxstudioFrameworkPath)\DotLiquid.dll</HintPath>
			<Private>True</Private>
		</Reference>
		<Reference Include="HtmlAgilityPack">
			<SpecificVersion>False</SpecificVersion>
			<HintPath>$(AdxstudioFrameworkPath)\HtmlAgilityPack.dll</HintPath>
			<Private>True</Private>
		</Reference>
		<Reference Include="ICSharpCode.SharpZipLib">
			<SpecificVersion>False</SpecificVersion>
			<HintPath>$(AdxstudioFrameworkPath)\ICSharpCode.SharpZipLib.dll</HintPath>
			<Private>True</Private>
		</Reference>
		<Reference Include="Lucene.Net">
			<SpecificVersion>False</SpecificVersion>
			<HintPath>$(AdxstudioFrameworkPath)\Lucene.Net.dll</HintPath>
			<Private>True</Private>
		</Reference>
		<Reference Include="Lucene.Net.Contrib.Highlighter">
			<SpecificVersion>False</SpecificVersion>
			<HintPath>$(AdxstudioFrameworkPath)\Lucene.Net.Contrib.Highlighter.dll</HintPath>
			<Private>True</Private>
		</Reference>
		<Reference Include="Lucene.Net.Contrib.Memory">
			<SpecificVersion>False</SpecificVersion>
			<HintPath>$(AdxstudioFrameworkPath)\Lucene.Net.Contrib.Memory.dll</HintPath>
			<Private>True</Private>
		</Reference>
		<Reference Include="Lucene.Net.Contrib.Snowball">
			<SpecificVersion>False</SpecificVersion>
			<HintPath>$(AdxstudioFrameworkPath)\Lucene.Net.Contrib.Snowball.dll</HintPath>
			<Private>True</Private>
		</Reference>
		<Reference Include="Microsoft.AspNet.Identity.Core">
			<SpecificVersion>False</SpecificVersion>
			<HintPath>$(AdxstudioFrameworkPath)\Microsoft.AspNet.Identity.Core.dll</HintPath>
			<Private>True</Private>
		</Reference>
		<Reference Include="Microsoft.AspNet.Identity.Owin">
			<SpecificVersion>False</SpecificVersion>
			<HintPath>$(AdxstudioFrameworkPath)\Microsoft.AspNet.Identity.Owin.dll</HintPath>
			<Private>True</Private>
		</Reference>
		<Reference Include="Microsoft.Crm.Sdk.Proxy">
			<SpecificVersion>False</SpecificVersion>
			<HintPath>$(AdxstudioFrameworkPath)\Microsoft.Crm.Sdk.Proxy.dll</HintPath>
			<Private>True</Private>
		</Reference>
		<Reference Include="Microsoft.CSharp">
		</Reference>
		<Reference Include="Microsoft.Owin">
			<SpecificVersion>False</SpecificVersion>
			<HintPath>$(AdxstudioFrameworkPath)\Microsoft.Owin.dll</HintPath>
			<Private>True</Private>
		</Reference>
		<Reference Include="Microsoft.Owin.Host.SystemWeb">
			<SpecificVersion>False</SpecificVersion>
			<HintPath>$(AdxstudioFrameworkPath)\Microsoft.Owin.Host.SystemWeb.dll</HintPath>
			<Private>True</Private>
		</Reference>
		<Reference Include="Microsoft.Owin.Security">
			<SpecificVersion>False</SpecificVersion>
			<HintPath>$(AdxstudioFrameworkPath)\Microsoft.Owin.Security.dll</HintPath>
			<Private>True</Private>
		</Reference>
		<Reference Include="Microsoft.Owin.Security.Cookies">
			<SpecificVersion>False</SpecificVersion>
			<HintPath>$(AdxstudioFrameworkPath)\Microsoft.Owin.Security.Cookies.dll</HintPath>
			<Private>True</Private>
		</Reference>
		<Reference Include="Microsoft.Owin.Security.Facebook">
			<SpecificVersion>False</SpecificVersion>
			<HintPath>$(AdxstudioFrameworkPath)\Microsoft.Owin.Security.Facebook.dll</HintPath>
			<Private>True</Private>
		</Reference>
		<Reference Include="Microsoft.Owin.Security.Google">
			<SpecificVersion>False</SpecificVersion>
			<HintPath>$(AdxstudioFrameworkPath)\Microsoft.Owin.Security.Google.dll</HintPath>
			<Private>True</Private>
		</Reference>
		<Reference Include="Microsoft.Owin.Security.MicrosoftAccount">
			<SpecificVersion>False</SpecificVersion>
			<HintPath>$(AdxstudioFrameworkPath)\Microsoft.Owin.Security.MicrosoftAccount.dll</HintPath>
			<Private>True</Private>
		</Reference>
		<Reference Include="Microsoft.Owin.Security.OpenIdConnect">
			<SpecificVersion>False</SpecificVersion>
			<HintPath>$(AdxstudioFrameworkPath)\Microsoft.Owin.Security.OpenIdConnect.dll</HintPath>
			<Private>True</Private>
		</Reference>
		<Reference Include="Microsoft.Owin.Security.Twitter">
			<SpecificVersion>False</SpecificVersion>
			<HintPath>$(AdxstudioFrameworkPath)\Microsoft.Owin.Security.Twitter.dll</HintPath>
			<Private>True</Private>
		</Reference>
		<Reference Include="Microsoft.Owin.Security.WsFederation">
			<SpecificVersion>False</SpecificVersion>
			<HintPath>$(AdxstudioFrameworkPath)\Microsoft.Owin.Security.WsFederation.dll</HintPath>
			<Private>True</Private>
		</Reference>
		<Reference Include="Microsoft.SharePoint.Client">
			<SpecificVersion>False</SpecificVersion>
			<HintPath>$(AdxstudioFrameworkPath)\Microsoft.SharePoint.Client.dll</HintPath>
			<Private>True</Private>
		</Reference>
		<Reference Include="Microsoft.SharePoint.Client.Runtime">
			<SpecificVersion>False</SpecificVersion>
			<HintPath>$(AdxstudioFrameworkPath)\Microsoft.SharePoint.Client.Runtime.dll</HintPath>
			<Private>True</Private>
		</Reference>
		<Reference Include="Microsoft.Web.Infrastructure">
			<SpecificVersion>False</SpecificVersion>
			<HintPath>$(AdxstudioFrameworkPath)\Microsoft.Web.Infrastructure.dll</HintPath>
			<Private>True</Private>
		</Reference>
		<Reference Include="Microsoft.WindowsAzure.StorageClient">
			<SpecificVersion>False</SpecificVersion>
			<HintPath>$(AdxstudioFrameworkPath)\Microsoft.WindowsAzure.StorageClient.dll</HintPath>
			<Private>True</Private>
		</Reference>
		<Reference Include="Microsoft.Xrm.Client">
			<SpecificVersion>False</SpecificVersion>
			<HintPath>$(AdxstudioFrameworkPath)\Microsoft.Xrm.Client.dll</HintPath>
			<Private>True</Private>
		</Reference>
		<Reference Include="Microsoft.Xrm.Portal">
			<SpecificVersion>False</SpecificVersion>
			<HintPath>$(AdxstudioFrameworkPath)\Microsoft.Xrm.Portal.dll</HintPath>
			<Private>True</Private>
		</Reference>
		<Reference Include="Microsoft.Xrm.Portal.Files">
			<SpecificVersion>False</SpecificVersion>
			<HintPath>$(AdxstudioFrameworkPath)\Microsoft.Xrm.Portal.Files.dll</HintPath>
			<Private>True</Private>
		</Reference>
		<Reference Include="Microsoft.Xrm.Sdk">
			<SpecificVersion>False</SpecificVersion>
			<HintPath>$(AdxstudioFrameworkPath)\Microsoft.Xrm.Sdk.dll</HintPath>
			<Private>True</Private>
		</Reference>
		<Reference Include="Newtonsoft.Json">
			<SpecificVersion>False</SpecificVersion>
			<HintPath>$(AdxstudioFrameworkPath)\Newtonsoft.Json.dll</HintPath>
			<Private>True</Private>
		</Reference>
		<Reference Include="Owin">
			<SpecificVersion>False</SpecificVersion>
			<HintPath>$(AdxstudioFrameworkPath)\Owin.dll</HintPath>
			<Private>True</Private>
		</Reference>
		<Reference Include="ParatureSDK">
			<SpecificVersion>False</SpecificVersion>
			<HintPath>$(AdxstudioFrameworkPath)\ParatureSDK.dll</HintPath>
			<Private>True</Private>
		</Reference>
		<Reference Include="Recaptcha">
			<SpecificVersion>False</SpecificVersion>
			<HintPath>$(AdxstudioFrameworkPath)\Recaptcha.dll</HintPath>
			<Private>True</Private>
		</Reference>
		<Reference Include="System.Data.DataSetExtensions">
		</Reference>
		<Reference Include="System.Data.Services">
		</Reference>
		<Reference Include="System.IdentityModel" />
		<Reference Include="System.identitymodel.services" />
		<Reference Include="System.IdentityModel.Tokens.Jwt">
			<SpecificVersion>False</SpecificVersion>
			<HintPath>$(AdxstudioFrameworkPath)\System.IdentityModel.Tokens.Jwt.dll</HintPath>
			<Private>True</Private>
		</Reference>
		<Reference Include="System.Net.Http">
		</Reference>
		<Reference Include="System.Net.Http.Formatting">
			<SpecificVersion>False</SpecificVersion>
			<HintPath>$(AdxstudioFrameworkPath)\System.Net.Http.Formatting.dll</HintPath>
			<Private>True</Private>
		</Reference>
		<Reference Include="System.Runtime.Serialization">
		</Reference>
		<Reference Include="System.ServiceModel">
		</Reference>
		<Reference Include="System.ServiceModel.Web">
		</Reference>
		<Reference Include="System.Threading.Tasks.Dataflow">
			<SpecificVersion>False</SpecificVersion>
			<HintPath>$(AdxstudioFrameworkPath)\System.Threading.Tasks.Dataflow.dll</HintPath>
			<Private>True</Private>
		</Reference>
		<Reference Include="System.Web.DynamicData">
		</Reference>
		<Reference Include="System.Web.Entity">
		</Reference>
		<Reference Include="System.Web.ApplicationServices">
		</Reference>
		<Reference Include="System.ComponentModel.DataAnnotations">
		</Reference>
		<Reference Include="System">
		</Reference>
		<Reference Include="System.Data">
		</Reference>
		<Reference Include="System.Web.Extensions">
		</Reference>
		<Reference Include="System.Web.Helpers">
			<SpecificVersion>False</SpecificVersion>
			<HintPath>$(AdxstudioFrameworkPath)\System.Web.Helpers.dll</HintPath>
			<Private>True</Private>
		</Reference>
		<Reference Include="System.Web.Http">
			<SpecificVersion>False</SpecificVersion>
			<HintPath>$(AdxstudioFrameworkPath)\System.Web.Http.dll</HintPath>
			<Private>True</Private>
		</Reference>
		<Reference Include="System.Web.Http.WebHost">
			<SpecificVersion>False</SpecificVersion>
			<HintPath>$(AdxstudioFrameworkPath)\System.Web.Http.WebHost.dll</HintPath>
			<Private>True</Private>
		</Reference>
		<Reference Include="System.Web.Mvc">
			<SpecificVersion>False</SpecificVersion>
			<HintPath>$(AdxstudioFrameworkPath)\System.Web.Mvc.dll</HintPath>
			<Private>True</Private>
		</Reference>
		<Reference Include="System.Web.Optimization">
			<SpecificVersion>False</SpecificVersion>
			<HintPath>$(AdxstudioFrameworkPath)\System.Web.Optimization.dll</HintPath>
			<Private>True</Private>
		</Reference>
		<Reference Include="System.Web.Razor">
			<SpecificVersion>False</SpecificVersion>
			<HintPath>$(AdxstudioFrameworkPath)\System.Web.Razor.dll</HintPath>
			<Private>True</Private>
		</Reference>
		<Reference Include="System.Web.WebPages">
			<SpecificVersion>False</SpecificVersion>
			<HintPath>$(AdxstudioFrameworkPath)\System.Web.WebPages.dll</HintPath>
			<Private>True</Private>
		</Reference>
		<Reference Include="System.Web.WebPages.Deployment">
			<SpecificVersion>False</SpecificVersion>
			<HintPath>$(AdxstudioFrameworkPath)\System.Web.WebPages.Deployment.dll</HintPath>
			<Private>True</Private>
		</Reference>
		<Reference Include="System.Web.WebPages.Razor">
			<SpecificVersion>False</SpecificVersion>
			<HintPath>$(AdxstudioFrameworkPath)\System.Web.WebPages.Razor.dll</HintPath>
			<Private>True</Private>
		</Reference>
		<Reference Include="System.Drawing">
		</Reference>
		<Reference Include="System.Web">
		</Reference>
		<Reference Include="System.Xml">
		</Reference>
		<Reference Include="System.Configuration">
		</Reference>
		<Reference Include="System.Web.Services">
		</Reference>
		<Reference Include="System.EnterpriseServices">
		</Reference>
		<Reference Include="System.Xml.Linq">
		</Reference>
		<Reference Include="WebGrease">
			<SpecificVersion>False</SpecificVersion>
			<HintPath>$(AdxstudioFrameworkPath)\WebGrease.dll</HintPath>
			<Private>True</Private>
		</Reference>
		<Reference Include="WindowsBase" />
		<Reference Include="Azure.Core">
			<SpecificVersion>False</SpecificVersion>
			<HintPath>$(AdxstudioFrameworkPath)\Azure.Core.dll</HintPath>
			<Private>True</Private>
		</Reference>
		<Reference Include="Azure.Core.Amqp">
			<SpecificVersion>False</SpecificVersion>
			<HintPath>$(AdxstudioFrameworkPath)\Azure.Core.Amqp.dll</HintPath>
			<Private>True</Private>
		</Reference>
		<Reference Include="Azure.Messaging.ServiceBus">
			<SpecificVersion>False</SpecificVersion>
			<HintPath>$(AdxstudioFrameworkPath)\Azure.Messaging.ServiceBus.dll</HintPath>
			<Private>True</Private>
		</Reference>
		<Reference Include="Azure.Storage.Blobs">
			<SpecificVersion>False</SpecificVersion>
			<HintPath>$(AdxstudioFrameworkPath)\Azure.Storage.Blobs.dll</HintPath>
			<Private>True</Private>
		</Reference>
		<Reference Include="Azure.Storage.Common">
			<SpecificVersion>False</SpecificVersion>
			<HintPath>$(AdxstudioFrameworkPath)\Azure.Storage.Common.dll</HintPath>
			<Private>True</Private>
		</Reference>
		<Reference Include="BoboBrowse.Net">
			<SpecificVersion>False</SpecificVersion>
			<HintPath>$(AdxstudioFrameworkPath)\BoboBrowse.Net.dll</HintPath>
			<Private>True</Private>
		</Reference>
		<Reference Include="BouncyCastle.Cryptography">
			<SpecificVersion>False</SpecificVersion>
			<HintPath>$(AdxstudioFrameworkPath)\BouncyCastle.Cryptography.dll</HintPath>
			<Private>True</Private>
		</Reference>
		<Reference Include="C5">
			<SpecificVersion>False</SpecificVersion>
			<HintPath>$(AdxstudioFrameworkPath)\C5.dll</HintPath>
			<Private>True</Private>
		</Reference>
		<Reference Include="Common.Logging">
			<SpecificVersion>False</SpecificVersion>
			<HintPath>$(AdxstudioFrameworkPath)\Common.Logging.dll</HintPath>
			<Private>True</Private>
		</Reference>
		<Reference Include="Common.Logging.Core">
			<SpecificVersion>False</SpecificVersion>
			<HintPath>$(AdxstudioFrameworkPath)\Common.Logging.Core.dll</HintPath>
			<Private>True</Private>
		</Reference>
		<Reference Include="FluentScheduler">
			<SpecificVersion>False</SpecificVersion>
			<HintPath>$(AdxstudioFrameworkPath)\FluentScheduler.dll</HintPath>
			<Private>True</Private>
		</Reference>
		<Reference Include="ITfoxtec.Identity.Saml2">
			<SpecificVersion>False</SpecificVersion>
			<HintPath>$(AdxstudioFrameworkPath)\ITfoxtec.Identity.Saml2.dll</HintPath>
			<Private>True</Private>
		</Reference>
		<Reference Include="JetBrains.Annotations">
			<SpecificVersion>False</SpecificVersion>
			<HintPath>$(AdxstudioFrameworkPath)\JetBrains.Annotations.dll</HintPath>
			<Private>True</Private>
		</Reference>
		<Reference Include="Lucene.Net.Contrib.Analyzers">
			<SpecificVersion>False</SpecificVersion>
			<HintPath>$(AdxstudioFrameworkPath)\Lucene.Net.Contrib.Analyzers.dll</HintPath>
			<Private>True</Private>
		</Reference>
		<Reference Include="Lucene.Net.Contrib.Core">
			<SpecificVersion>False</SpecificVersion>
			<HintPath>$(AdxstudioFrameworkPath)\Lucene.Net.Contrib.Core.dll</HintPath>
			<Private>True</Private>
		</Reference>
		<Reference Include="Lucene.Net.Contrib.FastVectorHighlighter">
			<SpecificVersion>False</SpecificVersion>
			<HintPath>$(AdxstudioFrameworkPath)\Lucene.Net.Contrib.FastVectorHighlighter.dll</HintPath>
			<Private>True</Private>
		</Reference>
		<Reference Include="Lucene.Net.Contrib.Queries">
			<SpecificVersion>False</SpecificVersion>
			<HintPath>$(AdxstudioFrameworkPath)\Lucene.Net.Contrib.Queries.dll</HintPath>
			<Private>True</Private>
		</Reference>
		<Reference Include="Lucene.Net.Contrib.Regex">
			<SpecificVersion>False</SpecificVersion>
			<HintPath>$(AdxstudioFrameworkPath)\Lucene.Net.Contrib.Regex.dll</HintPath>
			<Private>True</Private>
		</Reference>
		<Reference Include="Lucene.Net.Contrib.SimpleFacetedSearch">
			<SpecificVersion>False</SpecificVersion>
			<HintPath>$(AdxstudioFrameworkPath)\Lucene.Net.Contrib.SimpleFacetedSearch.dll</HintPath>
			<Private>True</Private>
		</Reference>
		<Reference Include="Lucene.Net.Contrib.SpellChecker">
			<SpecificVersion>False</SpecificVersion>
			<HintPath>$(AdxstudioFrameworkPath)\Lucene.Net.Contrib.SpellChecker.dll</HintPath>
			<Private>True</Private>
		</Reference>
		<Reference Include="Microsoft.AspNet.OData">
			<SpecificVersion>False</SpecificVersion>
			<HintPath>$(AdxstudioFrameworkPath)\Microsoft.AspNet.OData.dll</HintPath>
			<Private>True</Private>
		</Reference>
		<Reference Include="Microsoft.Azure.Amqp">
			<SpecificVersion>False</SpecificVersion>
			<HintPath>$(AdxstudioFrameworkPath)\Microsoft.Azure.Amqp.dll</HintPath>
			<Private>True</Private>
		</Reference>
		<Reference Include="Microsoft.Bcl.AsyncInterfaces">
			<SpecificVersion>False</SpecificVersion>
			<HintPath>$(AdxstudioFrameworkPath)\Microsoft.Bcl.AsyncInterfaces.dll</HintPath>
			<Private>True</Private>
		</Reference>
		<Reference Include="Microsoft.Bcl.Cryptography">
			<SpecificVersion>False</SpecificVersion>
			<HintPath>$(AdxstudioFrameworkPath)\Microsoft.Bcl.Cryptography.dll</HintPath>
			<Private>True</Private>
		</Reference>
		<Reference Include="Microsoft.Bcl.HashCode">
			<SpecificVersion>False</SpecificVersion>
			<HintPath>$(AdxstudioFrameworkPath)\Microsoft.Bcl.HashCode.dll</HintPath>
			<Private>True</Private>
		</Reference>
		<Reference Include="Microsoft.Bcl.TimeProvider">
			<SpecificVersion>False</SpecificVersion>
			<HintPath>$(AdxstudioFrameworkPath)\Microsoft.Bcl.TimeProvider.dll</HintPath>
			<Private>True</Private>
		</Reference>
		<Reference Include="Microsoft.Extensions.Caching.Abstractions">
			<SpecificVersion>False</SpecificVersion>
			<HintPath>$(AdxstudioFrameworkPath)\Microsoft.Extensions.Caching.Abstractions.dll</HintPath>
			<Private>True</Private>
		</Reference>
		<Reference Include="Microsoft.Extensions.Caching.Memory">
			<SpecificVersion>False</SpecificVersion>
			<HintPath>$(AdxstudioFrameworkPath)\Microsoft.Extensions.Caching.Memory.dll</HintPath>
			<Private>True</Private>
		</Reference>
		<Reference Include="Microsoft.Extensions.Configuration">
			<SpecificVersion>False</SpecificVersion>
			<HintPath>$(AdxstudioFrameworkPath)\Microsoft.Extensions.Configuration.dll</HintPath>
			<Private>True</Private>
		</Reference>
		<Reference Include="Microsoft.Extensions.Configuration.Abstractions">
			<SpecificVersion>False</SpecificVersion>
			<HintPath>$(AdxstudioFrameworkPath)\Microsoft.Extensions.Configuration.Abstractions.dll</HintPath>
			<Private>True</Private>
		</Reference>
		<Reference Include="Microsoft.Extensions.Configuration.Binder">
			<SpecificVersion>False</SpecificVersion>
			<HintPath>$(AdxstudioFrameworkPath)\Microsoft.Extensions.Configuration.Binder.dll</HintPath>
			<Private>True</Private>
		</Reference>
		<Reference Include="Microsoft.Extensions.DependencyInjection">
			<SpecificVersion>False</SpecificVersion>
			<HintPath>$(AdxstudioFrameworkPath)\Microsoft.Extensions.DependencyInjection.dll</HintPath>
			<Private>True</Private>
		</Reference>
		<Reference Include="Microsoft.Extensions.DependencyInjection.Abstractions">
			<SpecificVersion>False</SpecificVersion>
			<HintPath>$(AdxstudioFrameworkPath)\Microsoft.Extensions.DependencyInjection.Abstractions.dll</HintPath>
			<Private>True</Private>
		</Reference>
		<Reference Include="Microsoft.Extensions.Diagnostics.Abstractions">
			<SpecificVersion>False</SpecificVersion>
			<HintPath>$(AdxstudioFrameworkPath)\Microsoft.Extensions.Diagnostics.Abstractions.dll</HintPath>
			<Private>True</Private>
		</Reference>
		<Reference Include="Microsoft.Extensions.FileProviders.Abstractions">
			<SpecificVersion>False</SpecificVersion>
			<HintPath>$(AdxstudioFrameworkPath)\Microsoft.Extensions.FileProviders.Abstractions.dll</HintPath>
			<Private>True</Private>
		</Reference>
		<Reference Include="Microsoft.Extensions.Hosting.Abstractions">
			<SpecificVersion>False</SpecificVersion>
			<HintPath>$(AdxstudioFrameworkPath)\Microsoft.Extensions.Hosting.Abstractions.dll</HintPath>
			<Private>True</Private>
		</Reference>
		<Reference Include="Microsoft.Extensions.Http">
			<SpecificVersion>False</SpecificVersion>
			<HintPath>$(AdxstudioFrameworkPath)\Microsoft.Extensions.Http.dll</HintPath>
			<Private>True</Private>
		</Reference>
		<Reference Include="Microsoft.Extensions.Logging">
			<SpecificVersion>False</SpecificVersion>
			<HintPath>$(AdxstudioFrameworkPath)\Microsoft.Extensions.Logging.dll</HintPath>
			<Private>True</Private>
		</Reference>
		<Reference Include="Microsoft.Extensions.Logging.Abstractions">
			<SpecificVersion>False</SpecificVersion>
			<HintPath>$(AdxstudioFrameworkPath)\Microsoft.Extensions.Logging.Abstractions.dll</HintPath>
			<Private>True</Private>
		</Reference>
		<Reference Include="Microsoft.Extensions.ObjectPool">
			<SpecificVersion>False</SpecificVersion>
			<HintPath>$(AdxstudioFrameworkPath)\Microsoft.Extensions.ObjectPool.dll</HintPath>
			<Private>True</Private>
		</Reference>
		<Reference Include="Microsoft.Extensions.Options">
			<SpecificVersion>False</SpecificVersion>
			<HintPath>$(AdxstudioFrameworkPath)\Microsoft.Extensions.Options.dll</HintPath>
			<Private>True</Private>
		</Reference>
		<Reference Include="Microsoft.Extensions.Primitives">
			<SpecificVersion>False</SpecificVersion>
			<HintPath>$(AdxstudioFrameworkPath)\Microsoft.Extensions.Primitives.dll</HintPath>
			<Private>True</Private>
		</Reference>
		<Reference Include="Microsoft.Graph">
			<SpecificVersion>False</SpecificVersion>
			<HintPath>$(AdxstudioFrameworkPath)\Microsoft.Graph.dll</HintPath>
			<Private>True</Private>
		</Reference>
		<Reference Include="Microsoft.Graph.Core">
			<SpecificVersion>False</SpecificVersion>
			<HintPath>$(AdxstudioFrameworkPath)\Microsoft.Graph.Core.dll</HintPath>
			<Private>True</Private>
		</Reference>
		<Reference Include="Microsoft.IO.RecyclableMemoryStream">
			<SpecificVersion>False</SpecificVersion>
			<HintPath>$(AdxstudioFrameworkPath)\Microsoft.IO.RecyclableMemoryStream.dll</HintPath>
			<Private>True</Private>
		</Reference>
		<Reference Include="Microsoft.Identity.Client">
			<SpecificVersion>False</SpecificVersion>
			<HintPath>$(AdxstudioFrameworkPath)\Microsoft.Identity.Client.dll</HintPath>
			<Private>True</Private>
		</Reference>
		<Reference Include="Microsoft.Identity.Client.Extensions.Msal">
			<SpecificVersion>False</SpecificVersion>
			<HintPath>$(AdxstudioFrameworkPath)\Microsoft.Identity.Client.Extensions.Msal.dll</HintPath>
			<Private>True</Private>
		</Reference>
		<Reference Include="Microsoft.IdentityModel.Abstractions">
			<SpecificVersion>False</SpecificVersion>
			<HintPath>$(AdxstudioFrameworkPath)\Microsoft.IdentityModel.Abstractions.dll</HintPath>
			<Private>True</Private>
		</Reference>
		<Reference Include="Microsoft.IdentityModel.Clients.ActiveDirectory">
			<SpecificVersion>False</SpecificVersion>
			<HintPath>$(AdxstudioFrameworkPath)\Microsoft.IdentityModel.Clients.ActiveDirectory.dll</HintPath>
			<Private>True</Private>
		</Reference>
		<Reference Include="Microsoft.IdentityModel.JsonWebTokens">
			<SpecificVersion>False</SpecificVersion>
			<HintPath>$(AdxstudioFrameworkPath)\Microsoft.IdentityModel.JsonWebTokens.dll</HintPath>
			<Private>True</Private>
		</Reference>
		<Reference Include="Microsoft.IdentityModel.Logging">
			<SpecificVersion>False</SpecificVersion>
			<HintPath>$(AdxstudioFrameworkPath)\Microsoft.IdentityModel.Logging.dll</HintPath>
			<Private>True</Private>
		</Reference>
		<Reference Include="Microsoft.IdentityModel.Protocols">
			<SpecificVersion>False</SpecificVersion>
			<HintPath>$(AdxstudioFrameworkPath)\Microsoft.IdentityModel.Protocols.dll</HintPath>
			<Private>True</Private>
		</Reference>
		<Reference Include="Microsoft.IdentityModel.Protocols.OpenIdConnect">
			<SpecificVersion>False</SpecificVersion>
			<HintPath>$(AdxstudioFrameworkPath)\Microsoft.IdentityModel.Protocols.OpenIdConnect.dll</HintPath>
			<Private>True</Private>
		</Reference>
		<Reference Include="Microsoft.IdentityModel.Protocols.WsFederation">
			<SpecificVersion>False</SpecificVersion>
			<HintPath>$(AdxstudioFrameworkPath)\Microsoft.IdentityModel.Protocols.WsFederation.dll</HintPath>
			<Private>True</Private>
		</Reference>
		<Reference Include="Microsoft.IdentityModel.Tokens">
			<SpecificVersion>False</SpecificVersion>
			<HintPath>$(AdxstudioFrameworkPath)\Microsoft.IdentityModel.Tokens.dll</HintPath>
			<Private>True</Private>
		</Reference>
		<Reference Include="Microsoft.IdentityModel.Tokens.Saml">
			<SpecificVersion>False</SpecificVersion>
			<HintPath>$(AdxstudioFrameworkPath)\Microsoft.IdentityModel.Tokens.Saml.dll</HintPath>
			<Private>True</Private>
		</Reference>
		<Reference Include="Microsoft.IdentityModel.Validators">
			<SpecificVersion>False</SpecificVersion>
			<HintPath>$(AdxstudioFrameworkPath)\Microsoft.IdentityModel.Validators.dll</HintPath>
			<Private>True</Private>
		</Reference>
		<Reference Include="Microsoft.IdentityModel.Xml">
			<SpecificVersion>False</SpecificVersion>
			<HintPath>$(AdxstudioFrameworkPath)\Microsoft.IdentityModel.Xml.dll</HintPath>
			<Private>True</Private>
		</Reference>
		<Reference Include="Microsoft.Kiota.Abstractions">
			<SpecificVersion>False</SpecificVersion>
			<HintPath>$(AdxstudioFrameworkPath)\Microsoft.Kiota.Abstractions.dll</HintPath>
			<Private>True</Private>
		</Reference>
		<Reference Include="Microsoft.Kiota.Authentication.Azure">
			<SpecificVersion>False</SpecificVersion>
			<HintPath>$(AdxstudioFrameworkPath)\Microsoft.Kiota.Authentication.Azure.dll</HintPath>
			<Private>True</Private>
		</Reference>
		<Reference Include="Microsoft.Kiota.Http.HttpClientLibrary">
			<SpecificVersion>False</SpecificVersion>
			<HintPath>$(AdxstudioFrameworkPath)\Microsoft.Kiota.Http.HttpClientLibrary.dll</HintPath>
			<Private>True</Private>
		</Reference>
		<Reference Include="Microsoft.Kiota.Serialization.Form">
			<SpecificVersion>False</SpecificVersion>
			<HintPath>$(AdxstudioFrameworkPath)\Microsoft.Kiota.Serialization.Form.dll</HintPath>
			<Private>True</Private>
		</Reference>
		<Reference Include="Microsoft.Kiota.Serialization.Json">
			<SpecificVersion>False</SpecificVersion>
			<HintPath>$(AdxstudioFrameworkPath)\Microsoft.Kiota.Serialization.Json.dll</HintPath>
			<Private>True</Private>
		</Reference>
		<Reference Include="Microsoft.Kiota.Serialization.Multipart">
			<SpecificVersion>False</SpecificVersion>
			<HintPath>$(AdxstudioFrameworkPath)\Microsoft.Kiota.Serialization.Multipart.dll</HintPath>
			<Private>True</Private>
		</Reference>
		<Reference Include="Microsoft.Kiota.Serialization.Text">
			<SpecificVersion>False</SpecificVersion>
			<HintPath>$(AdxstudioFrameworkPath)\Microsoft.Kiota.Serialization.Text.dll</HintPath>
			<Private>True</Private>
		</Reference>
		<Reference Include="Microsoft.OData.Core">
			<SpecificVersion>False</SpecificVersion>
			<HintPath>$(AdxstudioFrameworkPath)\Microsoft.OData.Core.dll</HintPath>
			<Private>True</Private>
		</Reference>
		<Reference Include="Microsoft.OData.Edm">
			<SpecificVersion>False</SpecificVersion>
			<HintPath>$(AdxstudioFrameworkPath)\Microsoft.OData.Edm.dll</HintPath>
			<Private>True</Private>
		</Reference>
		<Reference Include="Microsoft.Owin.Security.OAuth">
			<SpecificVersion>False</SpecificVersion>
			<HintPath>$(AdxstudioFrameworkPath)\Microsoft.Owin.Security.OAuth.dll</HintPath>
			<Private>True</Private>
		</Reference>
		<Reference Include="Microsoft.PowerPlatform.Dataverse.Client">
			<SpecificVersion>False</SpecificVersion>
			<HintPath>$(AdxstudioFrameworkPath)\Microsoft.PowerPlatform.Dataverse.Client.dll</HintPath>
			<Private>True</Private>
		</Reference>
		<Reference Include="Microsoft.Rest.ClientRuntime">
			<SpecificVersion>False</SpecificVersion>
			<HintPath>$(AdxstudioFrameworkPath)\Microsoft.Rest.ClientRuntime.dll</HintPath>
			<Private>True</Private>
		</Reference>
		<Reference Include="Microsoft.Spatial">
			<SpecificVersion>False</SpecificVersion>
			<HintPath>$(AdxstudioFrameworkPath)\Microsoft.Spatial.dll</HintPath>
			<Private>True</Private>
		</Reference>
		<Reference Include="Microsoft.Xrm.Sdk.Deployment">
			<SpecificVersion>False</SpecificVersion>
			<HintPath>$(AdxstudioFrameworkPath)\Microsoft.Xrm.Sdk.Deployment.dll</HintPath>
			<Private>True</Private>
		</Reference>
		<Reference Include="Microsoft.Xrm.Sdk.Workflow">
			<SpecificVersion>False</SpecificVersion>
			<HintPath>$(AdxstudioFrameworkPath)\Microsoft.Xrm.Sdk.Workflow.dll</HintPath>
			<Private>True</Private>
		</Reference>
		<Reference Include="Microsoft.Xrm.Tooling.Connector">
			<SpecificVersion>False</SpecificVersion>
			<HintPath>$(AdxstudioFrameworkPath)\Microsoft.Xrm.Tooling.Connector.dll</HintPath>
			<Private>True</Private>
		</Reference>
		<Reference Include="Newtonsoft.Json.Bson">
			<SpecificVersion>False</SpecificVersion>
			<HintPath>$(AdxstudioFrameworkPath)\Newtonsoft.Json.Bson.dll</HintPath>
			<Private>True</Private>
		</Reference>
		<Reference Include="Owin.Security.Providers.LinkedIn">
			<SpecificVersion>False</SpecificVersion>
			<HintPath>$(AdxstudioFrameworkPath)\Owin.Security.Providers.LinkedIn.dll</HintPath>
			<Private>True</Private>
		</Reference>
		<Reference Include="Owin.Security.Providers.Yahoo">
			<SpecificVersion>False</SpecificVersion>
			<HintPath>$(AdxstudioFrameworkPath)\Owin.Security.Providers.Yahoo.dll</HintPath>
			<Private>True</Private>
		</Reference>
		<Reference Include="Polly">
			<SpecificVersion>False</SpecificVersion>
			<HintPath>$(AdxstudioFrameworkPath)\Polly.dll</HintPath>
			<Private>True</Private>
		</Reference>
		<Reference Include="Polly.Core">
			<SpecificVersion>False</SpecificVersion>
			<HintPath>$(AdxstudioFrameworkPath)\Polly.Core.dll</HintPath>
			<Private>True</Private>
		</Reference>
		<Reference Include="Std.UriTemplate">
			<SpecificVersion>False</SpecificVersion>
			<HintPath>$(AdxstudioFrameworkPath)\Std.UriTemplate.dll</HintPath>
			<Private>True</Private>
		</Reference>
		<Reference Include="System.Buffers">
			<SpecificVersion>False</SpecificVersion>
			<HintPath>$(AdxstudioFrameworkPath)\System.Buffers.dll</HintPath>
			<Private>True</Private>
		</Reference>
		<Reference Include="System.ClientModel">
			<SpecificVersion>False</SpecificVersion>
			<HintPath>$(AdxstudioFrameworkPath)\System.ClientModel.dll</HintPath>
			<Private>True</Private>
		</Reference>
		<Reference Include="System.ComponentModel.Annotations">
			<SpecificVersion>False</SpecificVersion>
			<HintPath>$(AdxstudioFrameworkPath)\System.ComponentModel.Annotations.dll</HintPath>
			<Private>True</Private>
		</Reference>
		<Reference Include="System.Diagnostics.DiagnosticSource">
			<SpecificVersion>False</SpecificVersion>
			<HintPath>$(AdxstudioFrameworkPath)\System.Diagnostics.DiagnosticSource.dll</HintPath>
			<Private>True</Private>
		</Reference>
		<Reference Include="System.Formats.Asn1">
			<SpecificVersion>False</SpecificVersion>
			<HintPath>$(AdxstudioFrameworkPath)\System.Formats.Asn1.dll</HintPath>
			<Private>True</Private>
		</Reference>
		<Reference Include="System.IO">
			<SpecificVersion>False</SpecificVersion>
			<HintPath>$(AdxstudioFrameworkPath)\System.IO.dll</HintPath>
			<Private>True</Private>
		</Reference>
		<Reference Include="System.IO.FileSystem.AccessControl">
			<SpecificVersion>False</SpecificVersion>
			<HintPath>$(AdxstudioFrameworkPath)\System.IO.FileSystem.AccessControl.dll</HintPath>
			<Private>True</Private>
		</Reference>
		<Reference Include="System.IO.Hashing">
			<SpecificVersion>False</SpecificVersion>
			<HintPath>$(AdxstudioFrameworkPath)\System.IO.Hashing.dll</HintPath>
			<Private>True</Private>
		</Reference>
		<Reference Include="System.IO.Pipelines">
			<SpecificVersion>False</SpecificVersion>
			<HintPath>$(AdxstudioFrameworkPath)\System.IO.Pipelines.dll</HintPath>
			<Private>True</Private>
		</Reference>
		<Reference Include="System.IdentityModel.Tokens.Jwt">
			<SpecificVersion>False</SpecificVersion>
			<HintPath>$(AdxstudioFrameworkPath)\System.IdentityModel.Tokens.Jwt.dll</HintPath>
			<Private>True</Private>
		</Reference>
		<Reference Include="System.Memory">
			<SpecificVersion>False</SpecificVersion>
			<HintPath>$(AdxstudioFrameworkPath)\System.Memory.dll</HintPath>
			<Private>True</Private>
		</Reference>
		<Reference Include="System.Memory.Data">
			<SpecificVersion>False</SpecificVersion>
			<HintPath>$(AdxstudioFrameworkPath)\System.Memory.Data.dll</HintPath>
			<Private>True</Private>
		</Reference>
		<Reference Include="System.Net.Http.WinHttpHandler">
			<SpecificVersion>False</SpecificVersion>
			<HintPath>$(AdxstudioFrameworkPath)\System.Net.Http.WinHttpHandler.dll</HintPath>
			<Private>True</Private>
		</Reference>
		<Reference Include="System.Net.ServerSentEvents">
			<SpecificVersion>False</SpecificVersion>
			<HintPath>$(AdxstudioFrameworkPath)\System.Net.ServerSentEvents.dll</HintPath>
			<Private>True</Private>
		</Reference>
		<Reference Include="System.Numerics.Vectors">
			<SpecificVersion>False</SpecificVersion>
			<HintPath>$(AdxstudioFrameworkPath)\System.Numerics.Vectors.dll</HintPath>
			<Private>True</Private>
		</Reference>
		<Reference Include="System.Runtime">
			<SpecificVersion>False</SpecificVersion>
			<HintPath>$(AdxstudioFrameworkPath)\System.Runtime.dll</HintPath>
			<Private>True</Private>
		</Reference>
		<Reference Include="System.Runtime.CompilerServices.Unsafe">
			<SpecificVersion>False</SpecificVersion>
			<HintPath>$(AdxstudioFrameworkPath)\System.Runtime.CompilerServices.Unsafe.dll</HintPath>
			<Private>True</Private>
		</Reference>
		<Reference Include="System.Security.AccessControl">
			<SpecificVersion>False</SpecificVersion>
			<HintPath>$(AdxstudioFrameworkPath)\System.Security.AccessControl.dll</HintPath>
			<Private>True</Private>
		</Reference>
		<Reference Include="System.Security.Cryptography.Algorithms">
			<SpecificVersion>False</SpecificVersion>
			<HintPath>$(AdxstudioFrameworkPath)\System.Security.Cryptography.Algorithms.dll</HintPath>
			<Private>True</Private>
		</Reference>
		<Reference Include="System.Security.Cryptography.Encoding">
			<SpecificVersion>False</SpecificVersion>
			<HintPath>$(AdxstudioFrameworkPath)\System.Security.Cryptography.Encoding.dll</HintPath>
			<Private>True</Private>
		</Reference>
		<Reference Include="System.Security.Cryptography.Primitives">
			<SpecificVersion>False</SpecificVersion>
			<HintPath>$(AdxstudioFrameworkPath)\System.Security.Cryptography.Primitives.dll</HintPath>
			<Private>True</Private>
		</Reference>
		<Reference Include="System.Security.Cryptography.ProtectedData">
			<SpecificVersion>False</SpecificVersion>
			<HintPath>$(AdxstudioFrameworkPath)\System.Security.Cryptography.ProtectedData.dll</HintPath>
			<Private>True</Private>
		</Reference>
		<Reference Include="System.Security.Cryptography.X509Certificates">
			<SpecificVersion>False</SpecificVersion>
			<HintPath>$(AdxstudioFrameworkPath)\System.Security.Cryptography.X509Certificates.dll</HintPath>
			<Private>True</Private>
		</Reference>
		<Reference Include="System.Security.Principal.Windows">
			<SpecificVersion>False</SpecificVersion>
			<HintPath>$(AdxstudioFrameworkPath)\System.Security.Principal.Windows.dll</HintPath>
			<Private>True</Private>
		</Reference>
		<Reference Include="System.ServiceModel.Duplex">
			<SpecificVersion>False</SpecificVersion>
			<HintPath>$(AdxstudioFrameworkPath)\System.ServiceModel.Duplex.dll</HintPath>
			<Private>True</Private>
		</Reference>
		<Reference Include="System.ServiceModel.Http">
			<SpecificVersion>False</SpecificVersion>
			<HintPath>$(AdxstudioFrameworkPath)\System.ServiceModel.Http.dll</HintPath>
			<Private>True</Private>
		</Reference>
		<Reference Include="System.ServiceModel.Primitives">
			<SpecificVersion>False</SpecificVersion>
			<HintPath>$(AdxstudioFrameworkPath)\System.ServiceModel.Primitives.dll</HintPath>
			<Private>True</Private>
		</Reference>
		<Reference Include="System.ServiceModel.Security">
			<SpecificVersion>False</SpecificVersion>
			<HintPath>$(AdxstudioFrameworkPath)\System.ServiceModel.Security.dll</HintPath>
			<Private>True</Private>
		</Reference>
		<Reference Include="System.Text.Encodings.Web">
			<SpecificVersion>False</SpecificVersion>
			<HintPath>$(AdxstudioFrameworkPath)\System.Text.Encodings.Web.dll</HintPath>
			<Private>True</Private>
		</Reference>
		<Reference Include="System.Text.Json">
			<SpecificVersion>False</SpecificVersion>
			<HintPath>$(AdxstudioFrameworkPath)\System.Text.Json.dll</HintPath>
			<Private>True</Private>
		</Reference>
		<Reference Include="System.Threading.Tasks.Extensions">
			<SpecificVersion>False</SpecificVersion>
			<HintPath>$(AdxstudioFrameworkPath)\System.Threading.Tasks.Extensions.dll</HintPath>
			<Private>True</Private>
		</Reference>
	</ItemGroup>
</Project>
